### PR TITLE
Added args-parse

### PR DESCRIPTION
**Pull request by TrySound**
Hi, @coderhaoxin !
What do you think about ast?

I use similar in [postcss-value-parser](https://github.com/TrySound/postcss-value-parser)

### CODE REVIEW

**Comment by TrySound** [comment]
I can concat everything between commas there are more than one entities. You think it's a good way?

**Comment by TrySound** [comment]
```
//= if ("str" === dsf) => [{ type: 'expr', value: '"str" === dsf' }]
```
```
//= include('name', {}) => [{ type: 'string', value: 'name', { type: 'obj', value: '{}' } }]
```

**Comment by coderhaoxin** [comment]
LGTM

> I use similar in postcss-value-parser

If there are more normal use cases, maybe you can split it to another separate module.

**Comment by TrySound** [comment]
@coderhaoxin I want to make full parser soon. For now this thing is just but fix.

**Pull request closed without merging**
